### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by naku111** [JianghaoWu/SIFA-pytorch#3]
When I switched to my own dataset to run the experiment, I found that I needed more than 80 GB of running memory, and I don't know why it was so large. How about you when you run the experiment?

**Comment by JianghaoWu** [comment]
Please check your dataset, batch sites, image size and 2D or 3D. For my experiments, 10 gb is enough to run.





When I switched to my own dataset to run the experiment, I found that I needed more than 80 GB of running memory, and I don't know why it was so large. How about you when you run the experiment?

**Comment by naku111** [comment]
> Please check your dataset, batch sites, image size and 2D or 3D. For my experiments, 10 gb is enough to run. When I switched to my own dataset to run the experiment, I found that I needed more than 80 GB of running memory, and I don't know why it was so large. How about you when you run the experiment? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Thanks
